### ISSUE TITLE
DUI & HRServer: does not trigger onSessionStart event

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/DUI#1]
I think we should have `onSessionStart req` there as in the MiServer-class

**Comment by mbaas2** [comment]
Looking at this again (as I now needed the event) - it seems my commit dealt with the principles of handling the event...when it is triggered. But it currently is not fired - HRSessions are simple created in SimpleSessions with ⎕NEW w/o calling onSessionStart.
(We may not have a req to pass to it, but still it would be useful. Maybe HRSessions could use the current session as ⍵ when calling onSessionStart?)

**Comment by bpbecker** [comment]
Fixed by a09ad34
